INSERT INTO RESTAURANT (NAME, ZIP_CODE, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, REVIEW_SCORE) VALUES ('Chapel Pub', '97217', NULL, 4.2, 3, 3.6);

INSERT INTO REVIEW (DISPLAY_NAME, RESTAURANT_ID, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, COMMENT, REVIEW_STATUS) VALUES ('Akkazurami', 1, 2, NULL, 3, 'Decent food.', 'Approved');
INSERT INTO REVIEW (DISPLAY_NAME, RESTAURANT_ID, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, COMMENT, REVIEW_STATUS) VALUES ('Kashogrim', 1, 3, 3.5, 3, 'Decent food.', 'Rejected');
INSERT INTO REVIEW (DISPLAY_NAME, RESTAURANT_ID, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, COMMENT, REVIEW_STATUS) VALUES ('Kashogrim', 1, NULL, 2, 3, 'Decent food.', 'Pending');
INSERT INTO REVIEW (DISPLAY_NAME, RESTAURANT_ID, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, COMMENT, REVIEW_STATUS) VALUES ('Gerzhuzad', 1, 5, NULL, 3, 'Decent food.', 'Approved');
INSERT INTO REVIEW (DISPLAY_NAME, RESTAURANT_ID, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, COMMENT, REVIEW_STATUS) VALUES ('Akkazurami', 1, 3, 3, 3, 'Decent food.', 'Pending');

INSERT INTO USERS (DISPLAY_NAME, CITY, STATE, ZIP_CODE, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY) VALUES ('Kashogrim', 'Portland', 'Oregon', '97202', false, false, true);
INSERT INTO USERS (DISPLAY_NAME, CITY, STATE, ZIP_CODE, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY) VALUES ('Gerzhuzad', 'Portland', 'Oregon', '97202', false, false, true);
INSERT INTO USERS (DISPLAY_NAME, CITY, STATE, ZIP_CODE, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY) VALUES ('Akkazurami', 'Portland', 'Oregon', '97202', false, false, true);
